print("hello. Please input a dollar ammount for each expense.")
print("Please input rent")
rent = int(input())
print("Please enter electric bill")
electric  = int(input())
print("Please enter your water bill")
water = int(input())
print("please enter your internet bill")
internet = int(input())
print("Please enter your grocery bill")
grocery = int(input())
print("Please enter any other expenses")
other = int(input())
print("Here is your monthy spending amount")
print(rent + electric + water + internet + grocery + other)